### PR TITLE
fixed non-const size for automatic array

### PR DESCRIPTION
**Pull request by atraczyk**

### CODE REVIEW

**Comment by Sibras** [comment]
Im assuming that this fix is designed to enable support with older Visual Studio versions that dont support dynamic array allocation? In which case what version are you trying to support?

**Comment by atraczyk** [comment]
I'm using Community 2015 (Version 14.0.24720.00 w/Update 1). I can't find any documentation stating that C99 style variable length arrays are supported. I tried a few community suggestions including adding /TC compiler option with no success. Then I came across multiple references hinting that there is no support for VLAs in VS2015 (https://msdn.microsoft.com/en-us/library/zb1574zs.aspx). Should I have put an `#ifdef` block or done something else entirely?

**Comment by Sibras** [comment]
My bad, not sure what I was thinking there. For some reason my VS didnt rebuilt debug.c after DEBUG was defined and so was actually reporting a successful build. So thanks for pointing out the error.

The code should be in an ifdef so it only effects msvc and Ive previously used alloca instead of malloc so that it functions identically to the original code. Ive added a different patch into my own repo to make it easier to update.

**Comment by atraczyk** [comment]
Ok cheers.

**Pull request closed without merging**
